name: field_services_app
description: A field services application for technicians

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  sqflite: ^2.3.0
  uuid: ^4.1.0
  mobile_scanner: ^3.5.6
  image_picker: ^1.0.4
  signature: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_nfc_kit: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true