name: field_services_app
description: Field Services Technician App with RFID Integration

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  path: ^1.8.3

  # NFC/RFID - Using more stable alternative
  flutter_nfc_kit: ^3.3.1
  ndef: ^0.3.1

  # Barcode scanning
  mobile_scanner: ^3.5.2

  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.3

  # Permissions
  permission_handler: ^11.0.1

  # UI
  cupertino_icons: ^1.0.2

  # Signature
  signature: ^5.4.0

  # State management
  provider: ^6.0.5

  # Local storage alternative
  shared_preferences: ^2.2.2

  # JSON serialization
  json_annotation: ^4.8.1

  # UUID generation
  uuid: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/